name: Build Solution

on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore SteamRouteTool
    
    - name: Build
      run: dotnet build SteamRouteTool -c ${{ matrix.configuration }}


    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SteamRouteTool
        path: bin
