name: Build Solution

on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        #dotnet-version: 6.0.x
        dotnet-version: 4.7.2

    - name: Get Package
      run: | 
        C:\msys64\usr\bin\wget.exe https://github.com/JamesNK/Newtonsoft.Json/releases/download/13.0.3/Json130r3.zip
        7z e Json130r3.zip "Bin\net45\Newtonsoft.Json.dll" "-o SteamRouteTool"
    
    - name: Build
      run: dotnet build SteamRouteTool -c ${{ matrix.configuration }} --no-restore


    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SteamRouteTool
        path: bin
